// frontend/src/components/agent/ClassificationPanel.jsx
import { useState } from 'react';
import { SLA_TIERS, SENTIMENT_MAP } from '../../constants';

export default function ClassificationPanel({ complaint, onOverride }) {
  const [open, setOpen]    = useState(true);
  const [whyOpen, setWhy]  = useState(false);

  const rows = [
    { label: 'Complaint Type',    value: complaint.ai_complaint_type,  conf: complaint.ai_confidence_score },
    { label: 'Product Category',  value: complaint.product_category,   conf: 0.97 },
    { label: 'Severity (Tier)',   value: complaint.sla_tier,           conf: 0.95 },
    { label: 'Sentiment',         value: complaint.ai_sentiment,       conf: 0.89 },
  ];

  const triggers = complaint.ai_trigger_phrases || [];

  return (
    <div style={{ background: '#F8F9FA', borderRadius: 12, padding: 16, marginTop: 16 }}>
      {/* Title row */}
      <button onClick={() => setOpen(o => !o)} style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', width: '100%', background: 'none', border: 'none', cursor: 'pointer', padding: 0, marginBottom: 4 }}>
        <span
          title="Handled by XGBoost + DistilBERT (Layer 2–4) — deterministic and auditable. Not generated by the LLM. A regulator can trace exactly why this complaint was classified P1."
          style={{ fontSize: 13, fontWeight: 700, color: '#0A1628', cursor: 'help' }}
        >
          AI Classification — 4-Head Multi-Label
        </span>
        <span style={{ color: '#6B7280', fontSize: 12 }}>{open ? '▲' : '▼'}</span>
      </button>
      <p style={{ fontSize: 11, color: '#9CA3AF', margin: '0 0 10px' }}>
        XGBoost + DistilBERT (Layer 2–4) — deterministic, auditable. Not generated by the LLM.
      </p>

      {open && (
        <>
          {rows.map(row => (
            <div key={row.label} style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 10, flexWrap: 'wrap' }}>
              <span style={{ fontSize: 12, color: '#6B7280', width: 130, flexShrink: 0 }}>{row.label}</span>
              <span style={{ fontSize: 12, fontWeight: 700, color: '#0A1628', flex: 1 }}>{row.value}</span>
              {/* Confidence bar */}
              <div style={{ display: 'flex', alignItems: 'center', gap: 5 }}>
                <div style={{ width: 56, height: 6, borderRadius: 3, background: '#E5E7EB', overflow: 'hidden' }}>
                  <div style={{ width: `${(row.conf || 0) * 100}%`, height: '100%', background: '#00B4A6', borderRadius: 3 }} />
                </div>
                <span style={{ fontSize: 11, color: '#6B7280' }}>{Math.round((row.conf || 0) * 100)}%</span>
              </div>
              {/* Override dropdown */}
              <select
                onChange={e => onOverride(row.label, e.target.value)}
                defaultValue=""
                style={{ fontSize: 11, padding: '3px 8px', borderRadius: 6, border: '1px solid #D1D5DB', color: '#374151', cursor: 'pointer' }}
              >
                <option value="" disabled>Override ▾</option>
                <option value="P1">P1</option>
                <option value="P2">P2</option>
                <option value="P3">P3</option>
                <option value="P4">P4</option>
              </select>
            </div>
          ))}

          {/* Why this classification */}
          <div style={{ borderTop: '1px solid #E5E7EB', paddingTop: 10, marginTop: 4 }}>
            <button onClick={() => setWhy(o => !o)} style={{ display: 'flex', justifyContent: 'space-between', width: '100%', background: 'none', border: 'none', cursor: 'pointer', padding: 0 }}>
              <span style={{ fontSize: 12, fontWeight: 600, color: '#00B4A6' }}>Why this classification?</span>
              <span style={{ fontSize: 11, color: '#6B7280' }}>{whyOpen ? '▲' : '▼'}</span>
            </button>

            {whyOpen && (
              <div style={{ marginTop: 10 }}>
                {triggers.length > 0 ? (
                  <>
                    <p style={{ fontSize: 12, color: '#374151', lineHeight: 1.7 }}>
                      {complaint.complaint_text?.split(new RegExp(`(${triggers.join('|')})`, 'i')).map((part, i) =>
                        triggers.some(p => p.toLowerCase() === part.toLowerCase())
                          ? <mark key={i} style={{ background: '#FEF08A', borderRadius: 3, padding: '1px 3px' }}>{part}</mark>
                          : part
                      )}
                    </p>
                    <p style={{ fontSize: 11, color: '#9CA3AF', marginTop: 8 }}>
                      These phrases are from the Indian Banking Domain Ontology — 200+ product terms and escalation phrases across 6 regional languages.
                    </p>
                  </>
                ) : (
                  <p style={{ fontSize: 12, color: '#6B7280' }}>Standard classification based on product keywords and complaint type matching.</p>
                )}
              </div>
            )}
          </div>
        </>
      )}
    </div>
  );
}
