import { createContext, useContext, useMemo, useState } from 'react';

const LanguageContext = createContext(null);

const LANGS = {
    EN: 'EN',
    HI: 'हिं',
    TA: 'தமிழ்',
    MR: 'मराठी',
};

const DICT = {
    HI: {
        'File a Complaint': 'शिकायत दर्ज करें',
        'Track Complaint': 'शिकायत ट्रैक करें',
        Overview: 'अवलोकन',
        'SLA Monitor': 'SLA मॉनिटर',
        'RBI Reports': 'RBI रिपोर्ट्स',
        'Agent Performance': 'एजेंट प्रदर्शन',
        'My Queue': 'मेरी कतार',
        'All Complaints': 'सभी शिकायतें',
        Escalations: 'एस्केलेशन',
        'My Performance': 'मेरा प्रदर्शन',
        Logout: 'लॉगआउट',
        'State Bank of India': 'भारतीय स्टेट बैंक',
        'Dark mode': 'डार्क मोड',
        'Light mode': 'लाइट मोड',
        'Track My Complaints': 'मेरी शिकायतें ट्रैक करें',
        'No complaints filed yet': 'अभी तक कोई शिकायत दर्ज नहीं हुई',
        'File Another': 'एक और दर्ज करें',
        'View Details →': 'विवरण देखें →',
        Timeline: 'टाइमलाइन',
        "Bank's Response": 'बैंक का उत्तर',
        'How was your experience?': 'आपका अनुभव कैसा रहा?',
        'Submit Feedback': 'फीडबैक सबमिट करें',
        'Complaint Filed Successfully': 'शिकायत सफलतापूर्वक दर्ज हुई',
        'Track This Complaint': 'इस शिकायत को ट्रैक करें',
        'Generate Report': 'रिपोर्ट तैयार करें',
        'Generating…': 'तैयार हो रहा है…',
        'Overview Dashboard': 'ओवरव्यू डैशबोर्ड',
        'SLA Performance by Tier': 'स्तर अनुसार SLA प्रदर्शन',
        'SLA Monitor': 'SLA मॉनिटर',
        'Open Complaints — Sorted by SLA Deadline': 'खुली शिकायतें — SLA समयसीमा के अनुसार',
        'No open complaints found.': 'कोई खुली शिकायत नहीं मिली।',
        Escalations: 'एस्केलेशन',
        'My Performance': 'मेरा प्रदर्शन',
        'Loading...': 'लोड हो रहा है...',
        'Your Details': 'आपका विवरण',
        Complaint: 'शिकायत',
        Documents: 'दस्तावेज़',
        'Review & Submit': 'समीक्षा और जमा करें',
        'Complaint Details': 'शिकायत विवरण',
        'Complaint Channel': 'शिकायत चैनल',
        'Date of Incident *': 'घटना की तारीख *',
        'Supporting Documents': 'सहायक दस्तावेज़',
        '← Back': '← वापस',
        'Next →': 'आगे →',
        'Submit Complaint': 'शिकायत जमा करें',
        'Submitting…': 'जमा हो रहा है…',
        'Loading your complaints…': 'आपकी शिकायतें लोड हो रही हैं…',
        'Complaints filed under your account · {count} total': 'आपके खाते के अंतर्गत शिकायतें · कुल {count}',
        'Filter by reference number (e.g. CIQ-2026-000001)': 'रेफरेंस नंबर से फ़िल्टर करें (उदा. CIQ-2026-000001)',
        Clear: 'साफ़ करें',
        'Use the button below to file your first complaint.': 'अपनी पहली शिकायत दर्ज करने के लिए नीचे का बटन उपयोग करें।',
        'No complaint matching': 'मिलती-जुलती शिकायत',
        'found in your account.': 'आपके खाते में नहीं मिली।',
        'Loading complaint details…': 'शिकायत विवरण लोड हो रहा है…',
        '← Back to My Complaints': '← मेरी शिकायतों पर वापस',
        'Complaint not found.': 'शिकायत नहीं मिली।',
        'Thank you for your feedback ✓': 'आपके फीडबैक के लिए धन्यवाद ✓',
        'Your complaint has been received and classified by our AI pipeline.': 'आपकी शिकायत प्राप्त हो चुकी है और हमारे AI द्वारा वर्गीकृत की गई है।',
        'Priority:': 'प्राथमिकता:',
        'Expected resolution by:': 'अपेक्षित समाधान तिथि:',
        'Track This Complaint': 'इस शिकायत को ट्रैक करें',
        "We'll notify you via SMS and email as your complaint progresses.": 'शिकायत की प्रगति पर हम आपको SMS और ईमेल से सूचित करेंगे।',
        'Loading escalations...': 'एस्केलेशन लोड हो रहे हैं...',
        'Complaints with regulatory-risk language or high SLA breach probability.': 'नियामकीय जोखिम भाषा या उच्च SLA उल्लंघन संभावना वाली शिकायतें।',
        'No escalations at the moment.': 'फिलहाल कोई एस्केलेशन नहीं है।',
        Open: 'खोलें',
        'Failed to load queue.': 'कतार लोड नहीं हो सकी।',
        'Failed to load escalations.': 'एस्केलेशन लोड नहीं हो सके।',
        'Loading performance...': 'प्रदर्शन लोड हो रहा है...',
        'Live performance metrics for your assigned complaint work.': 'आपके असाइन किए गए कार्य के लाइव प्रदर्शन मेट्रिक्स।',
        'No performance data yet for this account.': 'इस खाते के लिए अभी प्रदर्शन डेटा उपलब्ध नहीं है।',
        Assigned: 'असाइन किए गए',
        Resolved: 'समाधान किए गए',
        'Avg Handle': 'औसत हैंडल',
        'Complaints by Product': 'उत्पाद अनुसार शिकायतें',
        'No product data available.': 'उत्पाद डेटा उपलब्ध नहीं है।',
        'Customer Sentiment Breakdown': 'ग्राहक भावना विवरण',
        Frustrated: 'निराश',
        Neutral: 'तटस्थ',
        Satisfied: 'संतुष्ट',
        'Failed to load analytics.': 'एनालिटिक्स लोड नहीं हो सके।',
        'Loading analytics…': 'एनालिटिक्स लोड हो रहे हैं…',
        'Total Open': 'कुल खुली',
        Complaints: 'शिकायतें',
        'SLA Breach Rate': 'SLA उल्लंघन दर',
        'This month': 'इस महीने',
        'Avg Resolution': 'औसत समाधान',
        'AI Automation': 'AI ऑटोमेशन',
        'CSAT Score': 'CSAT स्कोर',
        'Loading SLA data…': 'SLA डेटा लोड हो रहा है…',
        '{count} complaint{plural} at high breach risk — regulatory escalation imminent:': '{count} शिकायत{plural} उच्च उल्लंघन जोखिम पर — नियामकीय एस्केलेशन आसन्न:',
        'No open complaints found.': 'कोई खुली शिकायत नहीं मिली।',
        Unassigned: 'अनअसाइन्ड',
        'Reassigning…': 'पुनः असाइन हो रहा है…',
        Reassign: 'पुनः असाइन',
        'RBI Monthly Complaint Report — Auto-Generated': 'RBI मासिक शिकायत रिपोर्ट — स्वतः निर्मित',
        'This report previously required 40–60 staff hours/month to compile manually.': 'पहले यह रिपोर्ट मैन्युअली बनाने में 40–60 स्टाफ घंटे/माह लगते थे।',
        'ComplaintIQ generates it from live data in under 2 minutes.': 'ComplaintIQ इसे लाइव डेटा से 2 मिनट से कम में तैयार करता है।',
        '⏳ Generating…': '⏳ तैयार हो रहा है…',
        '↓ Download PDF': '↓ PDF डाउनलोड',
        '↓ Download Excel': '↓ Excel डाउनलोड',
        '✓ Submitted to RBI': '✓ RBI को सबमिट',
        'Mark as Submitted to RBI': 'RBI को सबमिट के रूप में चिह्नित करें',
        'Submission History': 'सबमिशन इतिहास',
        'Failed to load agent performance.': 'एजेंट प्रदर्शन लोड नहीं हो सका।',
        'Loading agent performance...': 'एजेंट प्रदर्शन लोड हो रहा है...',
        'Agent Performance — March 2026': 'एजेंट प्रदर्शन — मार्च 2026',
        days: 'दिन',
        'No agent performance data available.': 'एजेंट प्रदर्शन डेटा उपलब्ध नहीं है।',
        'Account Number': 'खाता संख्या',
        'Your bank account number': 'आपका बैंक खाता नंबर',
        'Mobile Number': 'मोबाइल नंबर',
        '10-digit number starting with 6–9': '6–9 से शुरू होने वाला 10-अंकीय नंबर',
        'Email Address (Optional)': 'ईमेल पता (वैकल्पिक)',
        'your@email.com': 'your@email.com',
        'Preferred Language': 'पसंदीदा भाषा',
        'Product Category *': 'उत्पाद श्रेणी *',
        'Select a product': 'एक उत्पाद चुनें',
        'UPI Payment': 'UPI भुगतान',
        'NACH Mandate': 'NACH मंडेट',
        'Savings Account': 'बचत खाता',
        'Home Loan': 'होम लोन',
        'Credit Card': 'क्रेडिट कार्ड',
        'Fixed Deposit': 'फिक्स्ड डिपॉजिट',
        'NRE Account': 'NRE खाता',
        'PMJDY Account': 'PMJDY खाता',
        'Net Banking': 'नेट बैंकिंग',
        Other: 'अन्य',
        'ℹ National Automated Clearing House — handles EMI and recurring payments': 'ℹ नेशनल ऑटोमेटेड क्लियरिंग हाउस — EMI और आवर्ती भुगतानों को संभालता है',
        'ℹ Pradhan Mantri Jan-Dhan Yojana — government basic savings accounts': 'ℹ प्रधानमंत्री जन-धन योजना — सरकारी बेसिक बचत खाते',
        'Complaint Description *': 'शिकायत विवरण *',
        'Describe your complaint in detail (minimum 30 characters)…': 'अपनी शिकायत विस्तार से लिखें (कम से कम 30 अक्षर)…',
        '⚠ Your complaint mentions a regulatory body. We will treat this as P1 Priority and assign it to a senior agent within the next hour.': '⚠ आपकी शिकायत में नियामकीय संस्था का उल्लेख है। इसे P1 प्राथमिकता देकर अगले 1 घंटे में वरिष्ठ एजेंट को सौंपा जाएगा।',
        'Transaction Reference (Optional)': 'लेनदेन संदर्भ (वैकल्पिक)',
        'e.g. UPI/2026/03/15/4821': 'उदा. UPI/2026/03/15/4821',
        'Upload any screenshots, statements, or transaction proofs that support your complaint.': 'शिकायत समर्थन हेतु स्क्रीनशॉट, स्टेटमेंट या लेनदेन प्रमाण अपलोड करें।',
        Mobile: 'मोबाइल',
        Email: 'ईमेल',
        Product: 'उत्पाद',
        Channel: 'चैनल',
        Description: 'विवरण',
        'Incident Date': 'घटना तिथि',
        'Transaction Ref': 'लेनदेन संदर्भ',
        'File {n}': 'फ़ाइल {n}',
        Files: 'फ़ाइलें',
        'None attached': 'कोई संलग्न नहीं',
        'I confirm the information provided is accurate and complete': 'मैं पुष्टि करता/करती हूं कि दी गई जानकारी सही और पूर्ण है',
        'Failed to load complaint details.': 'शिकायत विवरण लोड नहीं हो सके।',
        'Failed to submit feedback. Please try again.': 'फीडबैक सबमिट नहीं हुआ। कृपया पुनः प्रयास करें।',
        'Tell us more (optional)': 'और बताएं (वैकल्पिक)',
        'Failed to load complaint.': 'शिकायत लोड नहीं हो सकी।',
        'Response sent ✓': 'उत्तर भेजा गया ✓',
        'Failed to send response. Please try again.': 'उत्तर भेजने में विफल। कृपया पुनः प्रयास करें।',
        'Classification overridden:': 'वर्गीकरण ओवरराइड किया गया:',
        'Loading complaint…': 'शिकायत लोड हो रही है…',
        '← Back to Queue': '← कतार में वापस',
        '← Queue': '← कतार',
        '⚠ ESCALATION RISK': '⚠ एस्केलेशन जोखिम',
        Reference: 'संदर्भ',
        Customer: 'ग्राहक',
        Account: 'खाता',
        Filed: 'दर्ज',
        'SLA Deadline': 'SLA समयसीमा',
        'Original Complaint': 'मूल शिकायत',
        'Previous Complaints': 'पिछली शिकायतें',
        System: 'सिस्टम',
        'Escalation risk logged. Contacting customer.': 'एस्केलेशन जोखिम दर्ज। ग्राहक से संपर्क किया जा रहा है।',
        'AI-Generated Draft Response': 'AI-निर्मित ड्राफ्ट उत्तर',
        'Grounded in:': 'आधारित:',
        'Bank Policy Documents': 'बैंक नीति दस्तावेज़',
        'Model: Llama 3.2 3B (Ollama — local)': 'मॉडल: Llama 3.2 3B (Ollama — स्थानीय)',
        'The LLM was constrained to only use information from retrieved bank policy documents. It cannot generate claims outside the knowledge base. (Layer 6)': 'LLM को केवल प्राप्त बैंक नीति दस्तावेज़ों की जानकारी तक सीमित रखा गया है। यह ज्ञान-आधार के बाहर दावे नहीं बना सकता। (लेयर 6)',
        '⚠ Compliance check flagged:': '⚠ अनुपालन जांच में चिह्नित:',
        'Checked by DistilBERT compliance classifier (50ms) — scans for unauthorised promises, incorrect timelines, PII, liability admissions. (Layer 7)': 'DistilBERT अनुपालन क्लासिफायर (50ms) द्वारा जांचा गया — अनधिकृत वादे, गलत टाइमलाइन, PII, दायित्व स्वीकारोक्ति स्कैन करता है। (लेयर 7)',
        'Possible Duplicate Detected': 'संभव डुप्लिकेट मिला',
        'Similarity:': 'समानता:',
        'semantic similarity': 'सिमेंटिक समानता',
        'Detected by FAISS cosine similarity on all-MiniLM-L6-v2 embeddings — not keyword match (Layer 3).': 'all-MiniLM-L6-v2 एम्बेडिंग्स पर FAISS cosine similarity से पहचाना गया — कीवर्ड मैच नहीं (लेयर 3)।',
        'Approve and Send Response': 'स्वीकृत करें और उत्तर भेजें',
        'Escalated to manager': 'प्रबंधक को एस्केलेट किया गया',
        'Escalate to Manager': 'प्रबंधक को एस्केलेट करें',
        'Marked as duplicate': 'डुप्लिकेट के रूप में चिह्नित',
        'Close as Duplicate': 'डुप्लिकेट के रूप में बंद करें',
        'Info request sent to customer': 'ग्राहक को अधिक जानकारी अनुरोध भेजा गया',
        'Request More Info': 'अधिक जानकारी मांगें',
        'to agent id:': 'को एजेंट आईडी:',
        'Reassigned to': 'पुनः असाइन किया गया:',
        Agent: 'एजेंट',
        'Unknown Customer': 'अज्ञात ग्राहक',
        'XGBoost prediction (Layer 4) — based on time remaining, complaint status, and agent queue depth. Target: reduce breach rate below 3%.': 'XGBoost पूर्वानुमान (लेयर 4) — शेष समय, शिकायत स्थिति और एजेंट कतार गहराई पर आधारित। लक्ष्य: breach rate 3% से नीचे।',
    },
    TA: {
        'File a Complaint': 'புகார் பதிவு',
        'Track Complaint': 'புகார் நிலை',
        Overview: 'மேலோட்டம்',
        'SLA Monitor': 'SLA கண்காணிப்பு',
        'RBI Reports': 'RBI அறிக்கைகள்',
        'Agent Performance': 'முகவர் செயல்திறன்',
        'My Queue': 'என் வரிசை',
        'All Complaints': 'அனைத்து புகார்கள்',
        Escalations: 'உயர்வு வழக்குகள்',
        'My Performance': 'என் செயல்திறன்',
        Logout: 'வெளியேறு',
        'State Bank of India': 'இந்திய மாநில வங்கி',
        'Dark mode': 'டார்க் மோடு',
        'Light mode': 'லைட் மோடு',
        'Track My Complaints': 'என் புகார்களை கண்காணிக்க',
        'No complaints filed yet': 'இன்னும் புகார் பதிவு செய்யப்படவில்லை',
        'File Another': 'மற்றொன்றை பதிவு செய்',
        'View Details →': 'விவரங்கள் →',
        Timeline: 'நிகழ்வுகளின் வரிசை',
        "Bank's Response": 'வங்கியின் பதில்',
        'How was your experience?': 'உங்கள் அனுபவம் எப்படி?',
        'Submit Feedback': 'கருத்து அனுப்பு',
        'Complaint Filed Successfully': 'புகார் வெற்றிகரமாக பதிவு செய்யப்பட்டது',
        'Track This Complaint': 'இந்த புகாரை கண்காணிக்க',
        'Generate Report': 'அறிக்கை உருவாக்கு',
        'Generating…': 'உருவாகிறது…',
        'Overview Dashboard': 'மேலோட்ட டாஷ்போர்ட்',
        'SLA Performance by Tier': 'அடுக்கு வாரியான SLA செயல்திறன்',
        'Open Complaints — Sorted by SLA Deadline': 'திறந்த புகார்கள் — SLA நேரவரம்பு அடிப்படையில்',
        'No open complaints found.': 'திறந்த புகார்கள் இல்லை.',
        'Your Details': 'உங்கள் விவரங்கள்',
        Complaint: 'புகார்',
        Documents: 'ஆவணங்கள்',
        'Review & Submit': 'சரிபார்த்து சமர்ப்பி',
        'Complaint Details': 'புகார் விவரங்கள்',
        'Complaint Channel': 'புகார் சேனல்',
        'Date of Incident *': 'சம்பவ நாள் *',
        'Supporting Documents': 'ஆதார ஆவணங்கள்',
        '← Back': '← பின்',
        'Next →': 'அடுத்து →',
        'Submit Complaint': 'புகார் சமர்ப்பிக்க',
        'Submitting…': 'சமர்ப்பிக்கிறது…',
        'Loading your complaints…': 'உங்கள் புகார்கள் ஏற்றப்படுகிறது…',
        'Complaints filed under your account · {count} total': 'உங்கள் கணக்கில் உள்ள புகார்கள் · மொத்தம் {count}',
        'Filter by reference number (e.g. CIQ-2026-000001)': 'குறிப்பு எண்ணால் வடிகட்டு (எ.கா. CIQ-2026-000001)',
        Clear: 'அழி',
        'Use the button below to file your first complaint.': 'உங்கள் முதல் புகாரை பதிவு செய்ய கீழே உள்ள பொத்தானை பயன்படுத்தவும்.',
        'Loading complaint details…': 'புகார் விவரங்கள் ஏற்றப்படுகிறது…',
        '← Back to My Complaints': '← என் புகார்களுக்கு திரும்பு',
        'Complaint not found.': 'புகார் கிடைக்கவில்லை.',
        'Thank you for your feedback ✓': 'உங்கள் கருத்துக்கு நன்றி ✓',
        'Priority:': 'முன்னுரிமை:',
        'Expected resolution by:': 'எதிர்பார்க்கப்படும் தீர்வு தேதி:',
        'Loading escalations...': 'உயர்வு வழக்குகள் ஏற்றப்படுகிறது...',
        'No escalations at the moment.': 'தற்போது உயர்வு வழக்குகள் இல்லை.',
        Open: 'திற',
        Assigned: 'ஒதுக்கப்பட்டது',
        Resolved: 'தீர்க்கப்பட்டது',
        'Avg Handle': 'சராசரி கையாளல்',
        'Complaints by Product': 'தயாரிப்பு வாரியான புகார்கள்',
        'No product data available.': 'தயாரிப்பு தரவு இல்லை.',
        'Customer Sentiment Breakdown': 'வாடிக்கையாளர் உணர்வு பகுப்பு',
        Frustrated: 'எரிச்சல்',
        Neutral: 'நடுநிலை',
        Satisfied: 'திருப்தி',
        'Loading analytics…': 'பகுப்பாய்வு ஏற்றப்படுகிறது…',
        'Total Open': 'மொத்த திறந்தவை',
        Complaints: 'புகார்கள்',
        'SLA Breach Rate': 'SLA மீறல் விகிதம்',
        'This month': 'இந்த மாதம்',
        'Avg Resolution': 'சராசரி தீர்வு',
        'AI Automation': 'AI தானியக்கம்',
        'CSAT Score': 'CSAT மதிப்பெண்',
        'Loading SLA data…': 'SLA தரவு ஏற்றப்படுகிறது…',
        'No open complaints found.': 'திறந்த புகார்கள் இல்லை.',
        Unassigned: 'ஒதுக்கப்படவில்லை',
        'Reassigning…': 'மறு ஒதுக்கீடு செய்கிறது…',
        Reassign: 'மறு ஒதுக்கு',
        'RBI Monthly Complaint Report — Auto-Generated': 'RBI மாதாந்திர புகார் அறிக்கை — தானாக உருவாக்கப்பட்டது',
        '⏳ Generating…': '⏳ உருவாக்கப்படுகிறது…',
        '↓ Download PDF': '↓ PDF பதிவிறக்கு',
        '↓ Download Excel': '↓ Excel பதிவிறக்கு',
        '✓ Submitted to RBI': '✓ RBIக்கு சமர்ப்பிக்கப்பட்டது',
        'Mark as Submitted to RBI': 'RBIக்கு சமர்ப்பிக்கப்பட்டதாக குறிக்க',
        'Submission History': 'சமர்ப்பிப்பு வரலாறு',
        'Loading agent performance...': 'முகவர் செயல்திறன் ஏற்றப்படுகிறது...',
        'Agent Performance — March 2026': 'முகவர் செயல்திறன் — மார்ச் 2026',
        days: 'நாட்கள்',
        'No agent performance data available.': 'முகவர் செயல்திறன் தரவு இல்லை.',
        'Account Number': 'கணக்கு எண்',
        'Mobile Number': 'மொபைல் எண்',
        'Email Address (Optional)': 'மின்னஞ்சல் முகவரி (விருப்பம்)',
        'Preferred Language': 'விருப்ப மொழி',
        'Product Category *': 'தயாரிப்பு வகை *',
        'Select a product': 'ஒரு தயாரிப்பை தேர்வு செய்க',
        'Complaint Description *': 'புகார் விளக்கம் *',
        'Transaction Reference (Optional)': 'பரிவர்த்தனை குறிப்பு (விருப்பம்)',
        Mobile: 'மொபைல்',
        Email: 'மின்னஞ்சல்',
        Product: 'தயாரிப்பு',
        Channel: 'சேனல்',
        Description: 'விளக்கம்',
        'Incident Date': 'சம்பவ தேதி',
        'Transaction Ref': 'பரிவர்த்தனை குறிப்பு',
        Files: 'கோப்புகள்',
        'None attached': 'இணைப்பு இல்லை',
        Reference: 'குறிப்பு',
        Customer: 'வாடிக்கையாளர்',
        Account: 'கணக்கு',
        Filed: 'பதிவு தேதி',
        'SLA Deadline': 'SLA கடைசி தேதி',
        'Original Complaint': 'அசல் புகார்',
        'Previous Complaints': 'முந்தைய புகார்கள்',
        'AI-Generated Draft Response': 'AI உருவாக்கிய வரைவு பதில்',
        'Grounded in:': 'அடிப்படை:',
        'Bank Policy Documents': 'வங்கி கொள்கை ஆவணங்கள்',
        'Similarity:': 'ஒற்றுமை:',
        'Approve and Send Response': 'அங்கீகரித்து பதில் அனுப்பு',
        'Escalate to Manager': 'மேலாளருக்கு உயர்த்து',
        'Close as Duplicate': 'நகல் என மூடு',
        'Request More Info': 'மேலும் தகவல் கோருக',
        'to agent id:': 'முகவர் ஐடிக்கு:',
        'Reassigned to': 'மீண்டும் ஒதுக்கப்பட்டது:',
        Agent: 'முகவர்',
        'Unknown Customer': 'அறியாத வாடிக்கையாளர்',
    },
    MR: {
        'File a Complaint': 'तक्रार नोंदवा',
        'Track Complaint': 'तक्रार ट्रॅक करा',
        Overview: 'आढावा',
        'SLA Monitor': 'SLA मॉनिटर',
        'RBI Reports': 'RBI अहवाल',
        'Agent Performance': 'एजंट कामगिरी',
        'My Queue': 'माझी क्यू',
        'All Complaints': 'सर्व तक्रारी',
        Escalations: 'एस्कलेशन्स',
        'My Performance': 'माझी कामगिरी',
        Logout: 'लॉगआउट',
        'State Bank of India': 'स्टेट बँक ऑफ इंडिया',
        'Dark mode': 'डार्क मोड',
        'Light mode': 'लाईट मोड',
        'Track My Complaints': 'माझ्या तक्रारी ट्रॅक करा',
        'No complaints filed yet': 'अजून तक्रार नोंदलेली नाही',
        'File Another': 'आणखी एक नोंदवा',
        'View Details →': 'तपशील पहा →',
        Timeline: 'टाइमलाइन',
        "Bank's Response": 'बँकेचे उत्तर',
        'How was your experience?': 'तुमचा अनुभव कसा होता?',
        'Submit Feedback': 'अभिप्राय सबमिट करा',
        'Complaint Filed Successfully': 'तक्रार यशस्वीरीत्या नोंदली',
        'Track This Complaint': 'ही तक्रार ट्रॅक करा',
        'Generate Report': 'अहवाल तयार करा',
        'Generating…': 'तयार होत आहे…',
        'Overview Dashboard': 'ओव्हरव्ह्यू डॅशबोर्ड',
        'SLA Performance by Tier': 'स्तरानुसार SLA कामगिरी',
        'Open Complaints — Sorted by SLA Deadline': 'खुल्या तक्रारी — SLA मुदतीनुसार',
        'No open complaints found.': 'खुल्या तक्रारी आढळल्या नाहीत.',
        'Your Details': 'तुमची माहिती',
        Complaint: 'तक्रार',
        Documents: 'दस्तऐवज',
        'Review & Submit': 'पुनरावलोकन व सबमिट',
        'Complaint Details': 'तक्रारीचा तपशील',
        'Complaint Channel': 'तक्रार चॅनेल',
        'Date of Incident *': 'घटनेची तारीख *',
        'Supporting Documents': 'पुरावा दस्तऐवज',
        '← Back': '← मागे',
        'Next →': 'पुढे →',
        'Submit Complaint': 'तक्रार सबमिट करा',
        'Submitting…': 'सबमिट होत आहे…',
        'Loading your complaints…': 'तुमच्या तक्रारी लोड होत आहेत…',
        'Complaints filed under your account · {count} total': 'तुमच्या खात्याखाली तक्रारी · एकूण {count}',
        'Filter by reference number (e.g. CIQ-2026-000001)': 'रेफरन्स नंबरने फिल्टर करा (उदा. CIQ-2026-000001)',
        Clear: 'साफ करा',
        'Use the button below to file your first complaint.': 'पहिली तक्रार नोंदवण्यासाठी खालील बटण वापरा.',
        'Loading complaint details…': 'तक्रार तपशील लोड होत आहे…',
        '← Back to My Complaints': '← माझ्या तक्रारींकडे परत',
        'Complaint not found.': 'तक्रार सापडली नाही.',
        'Thank you for your feedback ✓': 'तुमच्या अभिप्रायाबद्दल धन्यवाद ✓',
        'Priority:': 'प्राधान्य:',
        'Expected resolution by:': 'अपेक्षित निराकरण तारीख:',
        'Loading escalations...': 'एस्कलेशन्स लोड होत आहेत...',
        'No escalations at the moment.': 'सध्या एस्कलेशन्स नाहीत.',
        Open: 'उघडा',
        Assigned: 'नियुक्त',
        Resolved: 'निकाली',
        'Avg Handle': 'सरासरी हाताळणी',
        'Complaints by Product': 'उत्पादनानुसार तक्रारी',
        'No product data available.': 'उत्पादन डेटा उपलब्ध नाही.',
        'Customer Sentiment Breakdown': 'ग्राहक भावना विभाजन',
        Frustrated: 'निराश',
        Neutral: 'तटस्थ',
        Satisfied: 'समाधानी',
        'Loading analytics…': 'अॅनालिटिक्स लोड होत आहे…',
        'Total Open': 'एकूण खुल्या',
        Complaints: 'तक्रारी',
        'SLA Breach Rate': 'SLA उल्लंघन दर',
        'This month': 'या महिन्यात',
        'Avg Resolution': 'सरासरी निराकरण',
        'AI Automation': 'AI स्वयंचलन',
        'CSAT Score': 'CSAT स्कोर',
        'Loading SLA data…': 'SLA डेटा लोड होत आहे…',
        'No open complaints found.': 'खुल्या तक्रारी आढळल्या नाहीत.',
        Unassigned: 'अनियुक्त',
        'Reassigning…': 'पुन्हा नियुक्त करत आहे…',
        Reassign: 'पुन्हा नियुक्त करा',
        'RBI Monthly Complaint Report — Auto-Generated': 'RBI मासिक तक्रार अहवाल — स्वयंचलित',
        '⏳ Generating…': '⏳ तयार होत आहे…',
        '↓ Download PDF': '↓ PDF डाउनलोड',
        '↓ Download Excel': '↓ Excel डाउनलोड',
        '✓ Submitted to RBI': '✓ RBI ला सबमिट',
        'Mark as Submitted to RBI': 'RBI ला सबमिट म्हणून चिन्हांकित करा',
        'Submission History': 'सबमिशन इतिहास',
        'Loading agent performance...': 'एजंट कामगिरी लोड होत आहे...',
        'Agent Performance — March 2026': 'एजंट कामगिरी — मार्च 2026',
        days: 'दिवस',
        'No agent performance data available.': 'एजंट कामगिरी डेटा उपलब्ध नाही.',
        'Account Number': 'खाते क्रमांक',
        'Mobile Number': 'मोबाइल क्रमांक',
        'Email Address (Optional)': 'ईमेल पत्ता (पर्यायी)',
        'Preferred Language': 'प्राधान्य भाषा',
        'Product Category *': 'उत्पादन श्रेणी *',
        'Select a product': 'उत्पादन निवडा',
        'Complaint Description *': 'तक्रार वर्णन *',
        'Transaction Reference (Optional)': 'व्यवहार संदर्भ (पर्यायी)',
        Mobile: 'मोबाइल',
        Email: 'ईमेल',
        Product: 'उत्पादन',
        Channel: 'चॅनेल',
        Description: 'वर्णन',
        'Incident Date': 'घटनेची तारीख',
        'Transaction Ref': 'व्यवहार संदर्भ',
        Files: 'फाइल्स',
        'None attached': 'काही जोडलेले नाही',
        Reference: 'संदर्भ',
        Customer: 'ग्राहक',
        Account: 'खाते',
        Filed: 'नोंदवले',
        'SLA Deadline': 'SLA अंतिम मुदत',
        'Original Complaint': 'मूळ तक्रार',
        'Previous Complaints': 'मागील तक्रारी',
        'AI-Generated Draft Response': 'AI-निर्मित मसुदा प्रतिसाद',
        'Grounded in:': 'आधारित:',
        'Bank Policy Documents': 'बँक धोरण कागदपत्रे',
        'Similarity:': 'साम्य:',
        'Approve and Send Response': 'मंजूर करून प्रतिसाद पाठवा',
        'Escalate to Manager': 'व्यवस्थापकाकडे एस्कलेट करा',
        'Close as Duplicate': 'डुप्लिकेट म्हणून बंद करा',
        'Request More Info': 'अधिक माहिती मागवा',
        'to agent id:': 'एजंट आयडीला:',
        'Reassigned to': 'पुन्हा नियुक्त:',
        Agent: 'एजंट',
        'Unknown Customer': 'अज्ञात ग्राहक',
    },
};

export function LanguageProvider({ children }) {
    const [lang, setLang] = useState(() => localStorage.getItem('app_lang') || LANGS.EN);

    const value = useMemo(() => ({
        lang,
        setLang: (next) => {
            setLang(next);
            localStorage.setItem('app_lang', next);
        },
        labels: LANGS,
        t: (text) => {
            if (!text) return text;
            if (lang === LANGS.EN) return text;
            const byLang = DICT[Object.keys(LANGS).find((k) => LANGS[k] === lang)] || {};
            return byLang[text] || text;
        },
    }), [lang]);

    return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
    const ctx = useContext(LanguageContext);
    if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
    return ctx;
}
